app = "joebadcom"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[env]
  NODE_ENV = "production"
  PORT = "3000"
  HOSTNAME = "0.0.0.0"

# ISR requires persistent storage for cache
[mounts]
  source = "nextjs_cache"
  destination = "/app/.next/cache"
  processes = ["app"]

# Health check for the app
[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
    
  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "30s"
    restart_limit = 3
    timeout = "5s"